### ISSUE TITLE
Ported service to v5

### ISSUE THREAD

**Issue by christian-bromann** [klamping/wdio-applitools-service#3]
Hey,

I've ported this package to v5 (see https://github.com/webdriverio/v5/tree/master/packages/wdio-applitools-service). Is there any chance I can get NPM access to release the package together with the other packages? Also would you mind to deprecate this project and move forward with the one we have in v5?

Thank you a lot for making this. It was super easy to move the code to v5.

**Comment by klamping** [comment]
awesome! added you as an admin on the package. Will update the readme with info

**Comment by christian-bromann** [comment]
Thanks
